language: go

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.15.0

install:
  - go get -u -v github.com/therecipe/qt/cmd/...

script:
  - echo go test -v
  - echo go test -bench=.
  - golangci-lint run --enable-all
